services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - pnpm-store:/root/.local/share/pnpm/store
    command: sh -c "npx prisma migrate deploy && pnpm dev"

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pnpm-store:
